# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12fb1d432b19d606f7629c89385be7d74486fe57afdd27f4761cb97d63b55f61ef2a40d3d5e6ba1ddc5b18ad75b6225a797a87a14b1726f05357060c8d336237

test:
  secret_key_base: 81b4d8a7fd0360fb2cf007c63ee28319d68ddbe9f3e5f6f0370baffa63779ef6b364e76de98f2c6e1731f7ef2528d52c5cfe4b30429597f818e77b6ea265eaa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
